### ISSUE TITLE
Release a new version for composer installations

### ISSUE THREAD

**Issue by IchHabRecht** [manuelselbach/static_info_tables_fr#5]
Hi @manuelselbach,

Would you mind to release a new minor version for composer installations using the subtree split? It would be great to not depend on typo3-ter package and not on dev-master for production systems.

Thank you very much.

**Comment by manuelselbach** [comment]
Hi @IchHabRecht,

I released a new version 6.7.0 with support for 8.7 and 9.5, this also should be compatible with the subtree split.

Did I miss something?

If everything is fine, I will close this issue.
Looking for your feedback.

**Comment by IchHabRecht** [comment]
Hi @manuelselbach,

Works perfectly fine. Thank you very much for that quick update. Merry Christmas and a happy new year :-)
