### ISSUE TITLE
Language expression could not be parsed in v9

### ISSUE THREAD

**Issue by dhuf** [manuelselbach/static_info_tables_fr#6]
Message in the LOG: 

> Thu, 06 Feb 2020 10:59:26 +0100 [WARNING] request="e15a126d3e0c5" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"language = *fr*"}

https://github.com/manuelselbach/static_info_tables_fr/blob/master/Configuration/PageTSconfig/Suggest.tsconfig#L4

**Comment by manuelselbach** [comment]
@dhuf Thanks for reporting that issue. May I ask you to validate the changes committed to develop? If everything is fine from your side, I'll prepare an official release.

**Comment by dhuf** [comment]
@manuelselbach The log issue is fixed, but I have no idea where to test that feature ? Is it in the top search bar in the BE ?

**Comment by dhuf** [comment]
Thanks a lot for the quick fix !

**Comment by manuelselbach** [comment]
@dhuf Which feature are you talking about?

**Comment by dhuf** [comment]
Not sure what these configs are for, so don't know where to look for them:

TCEFORM.sys_language.static_lang_isocode.suggest.default.additionalSearchFields = lg_name_fr
TCEFORM.sys_language.static_lang_isocode.suggest.default.orderBy = lg_name_fr
TCEFORM.static_countries.cn_currency_uid.suggest.default.additionalSearchFields = cu_name_fr
TCEFORM.static_countries.cn_currency_uid.suggest.default.orderBy = cu_name_fr

**Comment by manuelselbach** [comment]
This is no new feature but was transferred into the "new" condition written in expression language. 

This is needed for the suggest wizard in the backend. Please, find all information in detail documented here: https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/PageTsconfig/TceForm.html#suggest

**Comment by dhuf** [comment]
Thanks, so then it should be fine. My issue was only the log

**Comment by manuelselbach** [comment]
It's released :) Thanks for the report and testing.
